### ISSUE TITLE
1.20.6 Support

### ISSUE THREAD

**Issue by h3nt41c0m1c5** [Gibatron/analog#1]
New minecraft version released was thinking any way it could get upgraded to 1.20.6?

**Comment by Gibatron** [comment]
I'll look into it into it, I know a lot has changed in the 1.20.x versions so I'm not terribly sure how much work that would be.

**Comment by h3nt41c0m1c5** [comment]
> I'll look into it into it, I know a lot has changed in the 1.20.x versions so I'm not terribly sure how much work that would be.

Would be great. Your mod sure seems interesting and didn't think anyone would make something like it but seems super cool!

**Comment by Gibatron** [comment]
I've updated Analog to 1.20.6

**Comment by h3nt41c0m1c5** [comment]
> I've updated Analog to 1.20.6

Will give it a shot and give feedback! Thank you.
