### ISSUE TITLE
Feature Request: Music Discs & Goat Horns play through speakers

### ISSUE THREAD

**Issue by cqm3ron** [Gibatron/analog#7]
I think this could be a fun feature for roleplaying purposes, if people want to for example make their own radio stations on a server.

I understand if this would be hard to implement, of course.

I should also add that I was thinking being able to play the custom ones from the Audio Player mod through here, but ig vanilla ones would be cool also.

**Comment by cqm3ron** [comment]
p.s. idk how to change the tag from an issue

**Comment by Gibatron** [comment]
This is something I really want to be possible but as far as I'm aware it's a very complicated feature to add. I'm not saying it won't happen but I'm also not saying it will happen.

**Comment by cqm3ron** [comment]
Fair enough lol

**Comment by Gibatron** [comment]
> I'm not saying it won't happen but I'm also not saying it will happen.

Apparently that means I spend two days straight implementing it. Should be out in a few days along with some other additions, barring any unforeseen circumstances.

**Comment by cqm3ron** [comment]
Damn, that's dedication!

**Comment by Gibatron** [comment]
Got everything ported a lot sooner than I expected. Version 1.2.0 is now out and supports playing vanilla music discs and custom AudioPlayer discs over the radio. Support for goat horns is not planned.
