### ISSUE TITLE
Suggestion: Allow custom/regular discs to be played VIA a transmitter

### ISSUE THREAD

**Issue by Nikkilectric** [Gibatron/analog#8]
Via the transmitter menu
![image](https://github.com/user-attachments/assets/378c824a-fa25-45da-9511-aa9557b97272)

There's free space at the bottom! Can we have the ability to insert & transmit music discs this way? On our server, the discs arent picked up half the time and it's really finicky.

Could we also have support for hoppers inserting & playing/removing finished discs like jukeboxes this way? Thank you ^^

**Comment by Gibatron** [comment]
I don't plan on implementing this, I would much rather this functionality stay a part of jukeboxes. I've been busy the past few days but I'll look into the issues with transmitting discs so this isn't necessary.
